-- Noctalia palette (semantic design keys)
-- GENERATED by Noctalia's "hyprland_lua" user template on every colorscheme change.

Colors = {
	primary = "rgba(e1e2d5ff)",
	secondary = "rgba(2d2a2eff)",
	tertiary = "rgba(2d2a2eff)",
	error = "rgba(d94a59ff)",
	surface = "rgba(1d1b1dff)",
	surface_variant = "rgba(262427ff)",
	on_surface = "rgba(e1e2d5ff)",
	outline = "rgba(4949ffff)",
}
